version: '3.8'

services:
  drone_norte:
    build:
      context: ..
      dockerfile: drone/Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - BASE_ORIGEM=NORTE
      - IP_BASE=${IP_PC_BASES}
      - PORTA_BASE_TCP=${PORTA_BASE_NORTE}
      - PORTA_BASE_UDP=${PORTA_BASE_NORTE_UDP}
      - PORTA_HEARTBEAT=7001            # <-- CORRIGIDO AQUI
      - HEARTBEAT_INTERVALO=${HEARTBEAT_INTERVALO}
      - DRONE_ID=${DRONE_ID:-DRONE-NORTE-AUTO}

  drone_sul:
    build:
      context: ..
      dockerfile: drone/Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - BASE_ORIGEM=SUL
      - IP_BASE=${IP_PC_BASES}
      - PORTA_BASE_TCP=${PORTA_BASE_SUL}
      - PORTA_BASE_UDP=${PORTA_BASE_SUL_UDP}
      - PORTA_HEARTBEAT=7011            # <-- CORRIGIDO AQUI
      - HEARTBEAT_INTERVALO=${HEARTBEAT_INTERVALO}
      - DRONE_ID=${DRONE_ID:-DRONE-SUL-AUTO}

  drone_leste:
    build:    
      context: ..
      dockerfile: drone/Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - BASE_ORIGEM=LESTE
      - IP_BASE=${IP_PC_BASES}
      - PORTA_BASE_TCP=${PORTA_BASE_LESTE}
      - PORTA_BASE_UDP=${PORTA_BASE_LESTE_UDP}
      - PORTA_HEARTBEAT=7021            # <-- CORRIGIDO AQUI
      - HEARTBEAT_INTERVALO=${HEARTBEAT_INTERVALO}
      - DRONE_ID=${DRONE_ID:-DRONE-LESTE-AUTO}

  drone_oeste:
    build:
      context: ..
      dockerfile: drone/Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - BASE_ORIGEM=OESTE
      - IP_BASE=${IP_PC_BASES}
      - PORTA_BASE_TCP=${PORTA_BASE_OESTE}
      - PORTA_BASE_UDP=${PORTA_BASE_OESTE_UDP}
      - PORTA_HEARTBEAT=7031            
      - HEARTBEAT_INTERVALO=${HEARTBEAT_INTERVALO}
      - DRONE_ID=${DRONE_ID:-DRONE-OESTE-AUTO}