# =============================================================
#  PC 1 — Brokers de Setor (S1 a S8)
#  Rodar com: docker compose -f docker-compose.setores.yml up
# =============================================================

services:

  broker_s1:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s1
    restart: unless-stopped
    ports:
      - "${PORTA_S1}:${PORTA_S1}"
    environment:
      SETOR_ID: "S1"
      SETOR_NOME: "Norte"
      MINHA_PORTA: "${PORTA_S1}"
      # Endereços das 4 bases (PC 2)
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      # Ordem de prioridade para este setor
      PRIORIDADE: "NORTE,OESTE,LESTE,SUL"
    networks:
      - ormuz_net

  broker_s2:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s2
    restart: unless-stopped
    ports:
      - "${PORTA_S2}:${PORTA_S2}"
    environment:
      SETOR_ID: "S2"
      SETOR_NOME: "Sul"
      MINHA_PORTA: "${PORTA_S2}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "SUL,LESTE,OESTE,NORTE"
    networks:
      - ormuz_net

  broker_s3:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s3
    restart: unless-stopped
    ports:
      - "${PORTA_S3}:${PORTA_S3}"
    environment:
      SETOR_ID: "S3"
      SETOR_NOME: "Leste"
      MINHA_PORTA: "${PORTA_S3}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "LESTE,NORTE,SUL,OESTE"
    networks:
      - ormuz_net

  broker_s4:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s4
    restart: unless-stopped
    ports:
      - "${PORTA_S4}:${PORTA_S4}"
    environment:
      SETOR_ID: "S4"
      SETOR_NOME: "Oeste"
      MINHA_PORTA: "${PORTA_S4}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "OESTE,NORTE,SUL,LESTE"
    networks:
      - ormuz_net

  broker_s5:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s5
    restart: unless-stopped
    ports:
      - "${PORTA_S5}:${PORTA_S5}"
    environment:
      SETOR_ID: "S5"
      SETOR_NOME: "Centro1"
      MINHA_PORTA: "${PORTA_S5}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "NORTE,LESTE,SUL,OESTE"
    networks:
      - ormuz_net

  broker_s6:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s6
    restart: unless-stopped
    ports:
      - "${PORTA_S6}:${PORTA_S6}"
    environment:
      SETOR_ID: "S6"
      SETOR_NOME: "Centro2"
      MINHA_PORTA: "${PORTA_S6}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "LESTE,NORTE,SUL,OESTE"
    networks:
      - ormuz_net

  broker_s7:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s7
    restart: unless-stopped
    ports:
      - "${PORTA_S7}:${PORTA_S7}"
    environment:
      SETOR_ID: "S7"
      SETOR_NOME: "Centro3"
      MINHA_PORTA: "${PORTA_S7}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "NORTE,SUL,LESTE,OESTE"
    networks:
      - ormuz_net

  broker_s8:
    build:
      context: ..
      dockerfile: setor/dockerfile
    container_name: broker_s8
    restart: unless-stopped
    ports:
      - "${PORTA_S8}:${PORTA_S8}"
    environment:
      SETOR_ID: "S8"
      SETOR_NOME: "Centro4"
      MINHA_PORTA: "${PORTA_S8}"
      IP_BASE_NORTE: "${IP_PC_BASES}"
      IP_BASE_SUL: "${IP_PC_BASES}"
      IP_BASE_LESTE: "${IP_PC_BASES}"
      IP_BASE_OESTE: "${IP_PC_BASES}"
      PORTA_BASE_NORTE: "${PORTA_BASE_NORTE}"
      PORTA_BASE_SUL: "${PORTA_BASE_SUL}"
      PORTA_BASE_LESTE: "${PORTA_BASE_LESTE}"
      PORTA_BASE_OESTE: "${PORTA_BASE_OESTE}"
      PRIORIDADE: "LESTE,SUL,NORTE,OESTE"
    networks:
      - ormuz_net

networks:
  ormuz_net:
    driver: bridge