FROM python:3.12-slim

WORKDIR /app

# Avisa ao Python para procurar módulos dentro da pasta shared também!
ENV PYTHONPATH="/app/shared"

# 1. Copia a pasta shared para dentro de /app/shared
COPY shared/ ./shared/

# 2. Copia TODOS os arquivos da pasta drone DIRETAMENTE para /app
COPY drone/ .

# 3. Inicia o drone
CMD ["python", "drone.py"]