services:

  sensor_s1:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s1
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S1"
      SETOR_ID: "S1"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S1}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s2:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s2
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S2"
      SETOR_ID: "S2"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S2}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s3:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s3
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S3"
      SETOR_ID: "S3"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S3}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s4:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s4
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S4"
      SETOR_ID: "S4"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S4}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s5:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s5
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S5"
      SETOR_ID: "S5"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S5}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s6:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s6
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S6"
      SETOR_ID: "S6"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S6}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s7:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s7
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S7"
      SETOR_ID: "S7"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S7}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

  sensor_s8:
    build:
      context: ..
      dockerfile: sensor/dockerfile
    container_name: sensor_s8
    restart: unless-stopped
    environment:
      SENSOR_ID: "SENSOR-S8"
      SETOR_ID: "S8"
      IP_BROKER_SETOR: "${IP_PC_SETORES}"
      PORTA_BROKER_SETOR: "${PORTA_S8}"
      INTERVALO_MIN: "5"
      INTERVALO_MAX: "15"
    networks:
      - ormuz_net

networks:
  ormuz_net:
    driver: bridge